#!/usr/bin/env python3
"""
使用 vaspkit 准备 POTCAR 文件的辅助脚本。
vaspkit 可以自动从 VASP 赝势库生成 POTCAR 文件。
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path


def check_vaspkit_installed():
    """检查 vaspkit 是否已安装。"""
    print("=" * 60)
    print("检查 vaspkit 安装...")
    print("=" * 60)
    
    # 检查 vaspkit 命令（可能在多个位置）
    vaspkit_paths = [
        "vaspkit",  # 在 PATH 中
        "/usr/local/bin/vaspkit",
        os.path.expanduser("~/vaspkit/bin/vaspkit"),
        os.path.expanduser("~/vaspkit.0.73/bin/vaspkit"),
        os.path.expanduser("~/vaspkit.0.72/bin/vaspkit"),
    ]
    
    # 也检查项目目录中是否有 vaspkit
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    vaspkit_manual_dir = project_root / "VASPKIT_manual"
    if vaspkit_manual_dir.exists():
        # 查找可能的 vaspkit 可执行文件
        for possible_dir in ["bin", "vaspkit", "vaspkit.0.73", "vaspkit.0.72"]:
            possible_path = vaspkit_manual_dir / possible_dir / "vaspkit"
            if possible_path.exists() and possible_path.is_file():
                vaspkit_paths.insert(0, str(possible_path))
    
    for vaspkit_cmd in vaspkit_paths:
        try:
            result = subprocess.run(
                [vaspkit_cmd, "-v"],
                capture_output=True,
                text=True,
                timeout=5
            )
            if result.returncode == 0:
                print(f"✓ vaspkit 已安装: {vaspkit_cmd}")
                if result.stdout.strip():
                    print(f"  版本信息: {result.stdout.strip()}")
                return vaspkit_cmd
        except FileNotFoundError:
            continue
        except subprocess.TimeoutExpired:
            continue
        except Exception:
            continue
    
    print("✗ 未找到 vaspkit 命令")
    print("\n如果 vaspkit 未安装，请参考:")
    print("  - GitHub: https://github.com/huangwenshi/vaspkit")
    print("  - 文档: https://vaspkit.com/")
    print("  - 项目中的手册: VASPKIT_manual/")
    return None


def check_vasp_pp_path():
    """检查 VASP 赝势库路径。"""
    print("\n" + "=" * 60)
    print("检查 VASP 赝势库路径...")
    print("=" * 60)
    
    # 常见路径
    common_paths = [
        os.environ.get("VASP_PP_PATH"),
        "/opt/vasp/potpaw_PBE",
        "/opt/vasp/potpaw_PBE.54",
        "/usr/local/vasp/potpaw_PBE",
        os.path.expanduser("~/vasp/potpaw_PBE"),
    ]
    
    for path in common_paths:
        if path and Path(path).exists():
            fe_path = Path(path) / "Fe"
            if fe_path.exists():
                print(f"✓ 找到 VASP 赝势库: {path}")
                return path
    
    print("✗ 未找到 VASP 赝势库")
    print("\n请设置 VASP_PP_PATH 环境变量:")
    print("  export VASP_PP_PATH=/path/to/potpaw_PBE")
    return None


def generate_potcar_with_vaspkit(elements, output_path, pp_path=None):
    """
    使用 vaspkit 生成 POTCAR 文件。
    
    vaspkit 使用方式:
    1. 交互式: vaspkit -> 选择功能 102
    2. 命令行: 需要创建临时文件或使用其他方法
    """
    print("\n" + "=" * 60)
    print("使用 vaspkit 生成 POTCAR...")
    print("=" * 60)
    
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # 方法 1: 使用 vaspkit 的交互式模式（通过脚本自动化）
    print(f"元素: {' '.join(elements)}")
    print(f"输出: {output_path}")
    
    # 创建临时目录用于 vaspkit
    temp_dir = project_root / "data" / "temp_vaspkit"
    temp_dir.mkdir(parents=True, exist_ok=True)
    
    try:
        # vaspkit 需要 POSCAR 文件来生成 POTCAR
        # 创建一个简单的 POSCAR 文件
        poscar_content = f"""Generated by vaspkit POTCAR generator
1.0
10.0 0.0 0.0
0.0 10.0 0.0
0.0 0.0 10.0
{' '.join(elements)}
1 1 1
Direct
0.0 0.0 0.0
"""
        
        temp_poscar = temp_dir / "POSCAR"
        with open(temp_poscar, 'w') as f:
            f.write(poscar_content)
        
        print(f"\n创建临时 POSCAR: {temp_poscar}")
        
        # 切换到临时目录
        original_dir = os.getcwd()
        os.chdir(temp_dir)
        
        # 方法: 使用 vaspkit 的非交互模式
        # vaspkit 0.71+ 版本: 功能 1 -> 103 (自动生成) 或 104 (手动选择)
        print("\n运行 vaspkit...")
        print("注意: vaspkit 需要交互式输入")
        print("vaspkit 0.71+ 版本使用:")
        print("  功能 1 -> 103 (自动生成 POTCAR)")
        print("  或 1 -> 104 (手动选择每个元素的赝势类型)")
        print("\n如果自动方式失败，请手动运行:")
        print(f"  cd {temp_dir}")
        print("  vaspkit")
        print("  然后选择: 1 -> 103 或 1 -> 104")
        
        # 尝试运行 vaspkit（功能 103 - 自动生成）
        # 注意: vaspkit 是交互式的，需要输入序列
        vaspkit_cmd = check_vaspkit_installed()
        if not vaspkit_cmd:
            print("错误: 未找到 vaspkit 可执行文件")
            return False
        
        try:
            # vaspkit 交互式输入序列: 1 (VASP Input Files Generator) -> 103 (Generate POTCAR)
            result = subprocess.run(
                [vaspkit_cmd],
                input="1\n103\n",
                text=True,
                capture_output=True,
                timeout=30,
                cwd=str(temp_dir)
            )
            
            if result.returncode == 0:
                # 检查是否生成了 POTCAR
                potcar_file = temp_dir / "POTCAR"
                if potcar_file.exists():
                    # 复制到目标位置
                    import shutil
                    shutil.copy(potcar_file, output_path)
                    print(f"✓ POTCAR 已生成: {output_path}")
                    return True
                else:
                    print("vaspkit 运行完成，但未找到生成的 POTCAR")
                    print("请检查 vaspkit 输出")
            else:
                print(f"vaspkit 返回错误: {result.returncode}")
                print(f"错误信息: {result.stderr}")
                
        except subprocess.TimeoutExpired:
            print("vaspkit 运行超时（可能需要交互式输入）")
        except Exception as e:
            print(f"运行 vaspkit 时出错: {e}")
        
        # 如果自动方式失败，提供手动说明
        print("\n" + "=" * 60)
        print("自动生成失败，请使用手动方式:")
        print("=" * 60)
        print(f"1. cd {temp_dir}")
        print("2. vaspkit")
        print("3. 选择功能: 1 (VASP Input Files Generator)")
        print("4. 选择子功能:")
        print("   - 103: 自动生成 POTCAR（推荐）")
        print("   - 104: 手动选择每个元素的赝势类型")
        print("5. 按照提示操作")
        print(f"6. 将生成的 POTCAR 复制到: {output_path}")
        print("\n推荐选择:")
        print("  - Fe: Fe_pv (包含 p 价电子，适合金属)")
        print("  - Si: Si (标准版本)")
        print("  - B: B (标准版本)")
        
    finally:
        os.chdir(original_dir)
    
    return False


def generate_potcar_manual_guide(elements, output_path):
    """生成手动使用 vaspkit 的指南。"""
    guide = f"""
# 使用 vaspkit 生成 POTCAR 文件 - 手动指南

## 前提条件

1. **配置 vaspkit 环境变量**
   ```bash
   # 如果还没有配置，复制配置文件模板
   cp /path/to/vaspkit/how_to_set_environment_variable ~/.vaspkit
   
   # 编辑配置文件
   vi ~/.vaspkit
   ```
   
   在 `~/.vaspkit` 中设置:
   ```
   PBE_PATH       /path/to/potpaw_PBE    # 您的 PBE 赝势库路径
   POTCAR_TYPE    PBE                    # 赝势类型
   RECOMMENDED_POTCAR  .TRUE.            # 使用推荐赝势
   ```

## 步骤 1: 准备 POSCAR 文件

vaspkit 需要一个 POSCAR 文件来生成 POTCAR。

已创建临时 POSCAR 文件在: data/temp_vaspkit/POSCAR

## 步骤 2: 运行 vaspkit

```bash
cd data/temp_vaspkit
vaspkit
```

## 步骤 3: 选择功能（vaspkit 0.71+ 版本）

在 vaspkit 主菜单中:
1. 输入 **1** 选择 `VASP Input Files Generator`
2. 然后选择:
   - **103** - 自动生成 POTCAR（推荐，使用推荐赝势）
   - **104** - 手动选择每个元素的赝势类型

## 步骤 4: 自动生成（功能 103）

如果选择 103:
- vaspkit 会自动读取 POSCAR 中的元素: {' '.join(elements)}
- 自动选择推荐的赝势版本
- 自动生成 POTCAR 文件

## 步骤 5: 手动选择（功能 104）

如果选择 104，需要为每个元素选择赝势版本:

按照提示依次输入:
- **Fe**: 输入 `Fe_pv`（推荐，包含 p 价电子，适合金属）
- **Si**: 输入 `Si`（标准版本）
- **B**: 输入 `B`（标准版本）

**注意**: 如果输入的赝势类型不存在，vaspkit 会提示重新输入。

## 步骤 6: 复制 POTCAR

生成后，复制到目标位置:

```bash
cp POTCAR {output_path}
```

## 验证

```bash
# 检查元素数量
grep -c "TITEL" {output_path}
# 应该输出: 3

# 检查元素顺序（必须与 POSCAR 匹配！）
grep "TITEL" {output_path}
# 应该显示:
# TITEL  = PAW Fe ...
# TITEL  = PAW Si ...
# TITEL  = PAW B ...

# 检查 ENCUT 推荐值
grep "ENMAX" {output_path}
```

## 赝势版本选择建议

| 元素 | 推荐版本 | 说明 |
|------|---------|------|
| **Fe** | `Fe_pv` | 包含 p 价电子，适合金属体系 |
| **Si** | `Si` | 标准版本，通常足够 |
| **B** | `B` | 标准版本，通常足够 |

## 常见问题

### Q: vaspkit 找不到赝势库

**A**: 检查 `~/.vaspkit` 文件中的 `PBE_PATH` 设置是否正确。

### Q: 元素顺序错误

**A**: vaspkit 会自动按照 POSCAR 中的元素顺序生成 POTCAR，确保 POSCAR 第 6 行是: {' '.join(elements)}

### Q: 生成的 POTCAR 缺少元素

**A**: 检查 POSCAR 文件格式，确保所有元素都在赝势库中存在。
"""
    return guide


def main():
    parser = argparse.ArgumentParser(
        description='使用 vaspkit 准备 POTCAR 文件',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        '--elements',
        nargs='+',
        default=['Fe', 'Si', 'B'],
        help='元素符号列表（必须与 POSCAR 顺序匹配）。默认: Fe Si B'
    )
    
    parser.add_argument(
        '--output',
        type=str,
        default='outputs/melt_quench_simulation/POTCAR',
        help='输出 POTCAR 文件路径。默认: outputs/melt_quench_simulation/POTCAR'
    )
    
    parser.add_argument(
        '--pp-path',
        type=str,
        help='VASP 赝势库路径（如果 vaspkit 需要）'
    )
    
    parser.add_argument(
        '--check-only',
        action='store_true',
        help='只检查 vaspkit 和 VASP 赝势库，不生成文件'
    )
    
    parser.add_argument(
        '--manual-guide',
        action='store_true',
        help='生成手动使用指南'
    )
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("vaspkit POTCAR 生成工具")
    print("=" * 60)
    
    # 检查 vaspkit
    vaspkit_cmd = check_vaspkit_installed()
    has_vaspkit = vaspkit_cmd is not None
    
    # 检查 VASP 赝势库
    pp_path = args.pp_path or check_vasp_pp_path()
    
    if args.check_only:
        if has_vaspkit:
            print(f"\n✓ vaspkit 可用: {vaspkit_cmd}")
        if pp_path:
            print(f"✓ VASP 赝势库: {pp_path}")
        sys.exit(0)
    
    if args.manual_guide:
        guide = generate_potcar_manual_guide(args.elements, args.output)
        guide_file = Path(__file__).parent.parent / "docs" / "VASPKIT_POTCAR_GUIDE.md"
        with open(guide_file, 'w', encoding='utf-8') as f:
            f.write(guide)
        print(f"\n手动指南已保存到: {guide_file}")
        return
    
    if not has_vaspkit:
        print("\n错误: 未找到 vaspkit")
        print("\n请:")
        print("1. 安装 vaspkit (https://github.com/huangwenshi/vaspkit)")
        print("2. 或将 vaspkit 添加到 PATH")
        print("3. 或使用 --manual-guide 查看手动指南")
        sys.exit(1)
    
    # 尝试生成 POTCAR
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    if not Path(args.output).is_absolute():
        output_path = project_root / args.output
    else:
        output_path = Path(args.output)
    
    success = generate_potcar_with_vaspkit(args.elements, output_path, pp_path)
    
    if not success:
        print("\n" + "=" * 60)
        print("建议使用手动方式:")
        print("=" * 60)
        print("运行以下命令生成手动指南:")
        print(f"python3 scripts/prepare_potcar_vaspkit.py --manual-guide --elements {' '.join(args.elements)}")
        print("\n或查看文档: docs/VASPKIT_POTCAR_GUIDE.md")


if __name__ == "__main__":
    main()

